name: mcsh_cbt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  provider: ^6.1.1
  go_router: ^14.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  http: ^1.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  graphql_flutter: ^5.2.0
  gql: ^1.0.1-alpha+1730759315362
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  fleather: ^1.22.0
  parchment: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
